### ISSUE TITLE
Multiple AzureMapDataSource or AzureMapBubbleLayer layers

### ISSUE THREAD

**Issue by redmorello** [rickyruiz/vue-azure-maps#14] opened 2020-03-26 14:58 UTC
It's not a bug, but I'm not sure how to add multiple layers to the map. I've got a working example in js and html that I'm trying to convert to vuejs.

I've added a AzureMapDataSource & AzureMapBubbleLayer component to the map, and can add points to the map ok. But in my previous example, we were grouping datapoints together based on a category, and changing the colour of the markers.

Is this possible in this projects current state?

**Comment by rickyruiz** [comment] 2020-03-26 21:10
@redmorello 

> Is this possible in this projects current state?

Yes, it should be, once I understand what you have on your previous example, I could try and replicate it using `vue-azure-maps`.

Could you share a minimal reproducible example of your previous working example? If not, is there any [AzureMapsCodeSample](https://azuremapscodesamples.azurewebsites.net/) that is similar to what you're trying to do?  

If you cannot create a minimal example or find any AzureMapCodeSample, please share some additional information, such as:
- How many data sources are you currently creating?
- Do you create an AzureMapBubbleLayer for each data source?

You can add N number of layers to an `AzureMapDataSource` component's default slot. You can also add multiple `AzureMapDataSource` components to the `AzureMap` component's default slot.

```html
    <!-- Create a Data Source -->
    <AzureMapDataSource
      :cluster="true"
      :cluster-radius="45"
      :cluster-max-zoom="15"
      @created="onDataSourceCreated"
    >
      <!-- Add Points to the Data Source -->
      <AzureMapPoint
        v-for="point in points"
        :key="point.properties.name"
        :longitude="point.longitude"
        :latitude="point.latitude"
      />
      <!-- Add a Bubble Layer to render the clustered Points stored in the Data Source -->
      <AzureMapBubbleLayer
        :options="bubbleLayerOptions"
      />
      <!-- Add N Bubble Layers -->
      <AzureMapBubbleLayer
        :options="nBubbleLayerOptions"
      />
      <!-- Add a Symbol Layer to render the Points stored in the Data Source -->
      <AzureMapSymbolLayer
        :options="symbolLayerOptions"
      />
      <!-- Add N Symbol Layers -->
      <AzureMapSymbolLayer
        :options="nSymbolLayerOptions"
      />
    </AzureMapDataSource>
```

**Comment by redmorello** [comment] 2020-03-27 09:49
Thanks for any help you can provide, much appreciated.

This is the code I've used previously. My API returns crime data, that I then group by crime category.

Then for each crime category array:

1. Create a maps datasource
2. Add the relevant grouped points to it
3. Add the datasource to the map
4. Assign a specific colour to the bubble layer and add the layer to the map

`
function renderMap(longitude, latitude, data) {
    var map = new atlas.Map('map', {
        center: [parseFloat(longitude), parseFloat(latitude)],
        zoom: 13,

        //Add your Azure Maps subscription key to the map SDK. Get an Azure Maps key at https://azure.com/maps
        authOptions: {
            authType: 'subscriptionKey',
            subscriptionKey: 'xxxxx'
        }
    });

    //Wait until the map resources are ready.
    map.events.add('ready', function () {

        /* Construct a zoom control*/
        var zoomControl = new atlas.control.ZoomControl();

        /* Add the zoom control to the map*/
        map.controls.add(zoomControl, {
            position: "bottom-right"
        });

        /* This is all the point data grouped by crime category     */
        /*Add point locations*/
        const groupedData = groupBy(data, d => d.category);
        console.log(groupedData);

        for (const [key, value] of groupedData.entries()) {
            
            var points = [];
            for (var i = 0; i < value.length; i++) {
                var longitude = parseFloat(value[i].location.longitude);
                var latitude = parseFloat(value[i].location.latitude);
                points.push(new atlas.data.Point([longitude, latitude]));
            }

            /*Create a data source and add it to the map*/
            var dataSource = new atlas.source.DataSource();
            map.sources.add(dataSource);
            /*Add multiple points to the data source*/
            dataSource.add(points);

            var colour;
            switch (key) {
                case "anti-social-behaviour":
                    colour = "#ff3300";
                break;
                case "bicycle-theft":
                    colour = "#66ff33";
                    break;
                case "burglary":
                    colour = "#0033cc";
                    break;
                case "criminal-damage-arson":
                    colour = "#9933ff";
                    break;
                case "drugs":
                    colour = "#660033";
                    break;
                case "other-theft":
                    colour = "#ffcc00";
                    break;
                case "robbery":
                    colour = "#cc6600";
                    break;
                case "shoplifting":
                    colour = "#ff6666";
                    break;
                case "theft-from-the-person":
                    colour = "#666633";
                    break;
                case "vehicle-crime":
                    colour = "#666699";
                    break;
                case "violent-crime":
                    colour = "#33cc33";
                    break;
                default:
                    // other-crime
                    colour = "#4288f7";
                    break;
            }

            //Create a bubble layer to render the filled in area of the circle, and add it to the map.*/
            var bubbleLayer = new atlas.layer.BubbleLayer(dataSource, null, {
                radius: 3,
                strokeColor: colour,
                strokeWidth: 2,
                color: colour
            });
            map.layers.add(bubbleLayer);
        }
    });
}`

**Comment by redmorello** [comment] 2020-03-27 13:16
I've fixed it in another way. I've used a single datasource & bubblelayer, added all my points into the AzureMapPoint and then changed the colour of each in the bubbleLayerOptions:

```
bubbleLayerOptions: {
        radius: 3,
        strokeColor: [
          "match",
          //Get the property to match.
          ["get", "category"],
          //List the values to match and the result to return for each match.
          "anti-social-behaviour",
          "#ff3300",
          "bicycle-theft",
          "#66ff33",
          "burglary",
          "#0033cc",
          "criminal-damage-arson",
          "#9933ff",
          "drugs",
          "#660033",
          "other-theft",
          "#ffcc00",
          "robbery",
          "#cc6600",
          "shoplifting",
          "#ff6666",
          "theft-from-the-person",
          "#666633",
          "vehicle-crime",
          "#666699",
          "violent-crime",
          "#33cc33",
          //Specify a default value to return if no match is found.
          "#4288f7"
        ],
        strokeWidth: 2,
        color: [
          "match",
          //Get the property to match.
          ["get", "category"],
          //List the values to match and the result to return for each match.
          "anti-social-behaviour",
          "#ff3300",
          "bicycle-theft",
          "#66ff33",
          "burglary",
          "#0033cc",
          "criminal-damage-arson",
          "#9933ff",
          "drugs",
          "#660033",
          "other-theft",
          "#ffcc00",
          "robbery",
          "#cc6600",
          "shoplifting",
          "#ff6666",
          "theft-from-the-person",
          "#666633",
          "vehicle-crime",
          "#666699",
          "violent-crime",
          "#33cc33",
          //Specify a default value to return if no match is found.
          "#4288f7"
        ]
      }
```

**Comment by rickyruiz** [comment] 2020-03-27 19:17
Here's a working CodeSandbox example using `vue-azure-maps`: 

**Make sure to use your Azure Map subscription key in the main.js file.**
https://codesandbox.io/s/vue-azure-maps-crimes-example-gbxif


In the example we're just rendering bubbles, I'm guessing you want to cluster the data and create html markers based on the data source points. Something like this [Azure Map Code Sample](https://azuremapscodesamples.azurewebsites.net/Bubble%20Layer/Point%20Clusters%20in%20Bubble%20Layer.html). For that you can use the [`<AzureMapBubbleLayer>` cluster properties](https://rickyruiz.github.io/vue-azure-maps/components/other/AzureMapDataSource.html#props), the [`<AzureMapHtmlMarker>`](https://rickyruiz.github.io/vue-azure-maps/components/other/AzureMapHtmlMarker.html) and color each marker by category.

The `<AzureMapHtmlMarker>` component documentation is not ready yet because I will most probably change the component. You will be able to pass a default slot instead of an `htmlContent` prop, for now you can pass a `color` prop which will use the default marker colored.

```html
<template
  v-for="(crime, index) in crimes"
>
    <!-- Add the point to the data source -->
    <AzureMapPoint
      :key="`point-${index}`"
      :longitude="parseFloat(crime.location.longitude)"
      :latitude="parseFloat(crime.location.latitude)"
      :properties="crime"
    />
    <!-- Add an Html marker -->
    <AzureMapHtmlMarker
      :key="`marker-${index}`"
      :color="color"
      :position="[parseFloat(crime.location.longitude), parseFloat(crime.location.latitude)]"
    />
 </template>
```

**Comment by rickyruiz** [comment] 2020-04-03 22:21
Closing for now, will reopen if further explanation is needed.

**Closed by rickyruiz** 2020-04-03 22:21 UTC
Labels: question
